### PR TITLE
Use latest libusbmuxd

### PR DESCRIPTION
**Pull request by eric**
Instead of embedding an old version of libusbmuxd, this uses the latest version from github via a submodule.

### CODE REVIEW

**Comment by eric** [comment]
I found that this does not work as-is — something has changed about how libusbmuxd works that doesn't make it connect. I'll have to look into it further.

**Comment by eric** [comment]
I continue to have confusing issues when running this branch, so it doesn't appear it fully works as-is, but there are many improvements in the latest that are not in the vendored version that make me believe it would be worth the effort to understand what has changed and fix it.

**Comment by wtsnz** [comment]
@eric Thanks so much for all the PRs. I am hoping to get around to reviewing and merging them into the project this week. 

As for the vendored usbmuxd, if I remember correctly, I used this fork of usbmuxd in order to get it to work with Windows: https://github.com/libimobiledevice-win32/usbmuxd

**Comment by wtsnz** [comment]
I've spent some time today updating the vendored libs - a precursor to add in libimobiledevice which will let us get the device names - in #69

**Comment by eric** [comment]
That’s great!

**Pull request closed without merging**
