### PR TITLE
Reduce video frame queue to 5 packets

### PR DESCRIPTION
**Pull request by eric**
This will hopefully prevent video lag. I've been running into many issues with lag over extended uses and I was hoping this would help.

Also, this solves potential memory leaks that happen when packets are dropped.

### CODE REVIEW

**Comment by wtsnz** [comment]
Thanks! Looks great.

What is the profile function code? Is it provided by OBS Studio?

**Comment by eric** [comment]
Yes, it's provided by OBS and is output to stdout on exit when you run OBS via the command line.

**Comment by wtsnz** [comment]
Sweet! 

Is it something that we can keep in the prod builds, or is it automatically ifdef'd out?

**Comment by eric** [comment]
It’s fine to keep in production builds. It’s used in the encoder plugins in OBS, etc.

**Comment by wtsnz** [comment]
Sweet - thanks for the clarification :)

**Pull request merged**
